import { BusinessCategoryPreset, BusinessType } from '../types';

export const BUSINESS_PRESETS: Record<BusinessType, BusinessCategoryPreset> = {
  barbershop: {
    id: 'barbershop',
    name: 'Barbershop & Pangkas Rambut',
    tagline: 'Potong rambut, styling, perawatan jenggot & produk pomade',
    icon: 'Scissors',
    identifierLabel: 'No. Kursi / Nama Klien',
    defaultStaffRoles: ['Capster / Barber', 'Barber Utama', 'Kasir'],
    defaultCategories: ['Haircut', 'Treatment', 'Body Cloud', 'Shaving & Grooming', 'Treatment & Cuci', 'Pewarnaan', 'Produk Rambut'],
    defaultPaymentMethods: ['Cash', 'QRIS', 'Debit / Transfer'],
    defaultItems: [
      {
        id: 'barber-t1',
        name: 'Treatment Scalp & Hair Repair',
        category: 'Treatment',
        price: 45000,
        type: 'service',
        reqStaffRole: 'Capster / Barber',
        available: true,
      },
      {
        id: 'barber-bc1',
        name: 'Body Cloud Head & Shoulder Massage',
        category: 'Body Cloud',
        price: 60000,
        type: 'service',
        reqStaffRole: 'Capster / Barber',
        available: true,
      },
      {
        id: 'barber-bc2',
        name: 'Body Cloud Aromatherapy Spa Mist',
        category: 'Body Cloud',
        price: 50000,
        type: 'service',
        reqStaffRole: 'Capster / Barber',
        available: true,
      },
      {
        id: 'barber-1',
        name: 'Potong Rambut Dewasa + Cuci',
        category: 'Haircut',
        price: 35000,
        type: 'service',
        reqStaffRole: 'Capster / Barber',
        available: true,
      },
      {
        id: 'barber-2',
        name: 'Potong Rambut Anak-Anak',
        category: 'Haircut',
        price: 25000,
        type: 'service',
        reqStaffRole: 'Capster / Barber',
        available: true,
      },
      {
        id: 'barber-3',
        name: 'Paket Gentleman (Cut + Wash + Pijat)',
        category: 'Haircut',
        price: 50000,
        type: 'service',
        reqStaffRole: 'Capster / Barber',
        available: true,
      },
      {
        id: 'barber-4',
        name: 'Cukur Kumis & Jenggot (Hot Towel)',
        category: 'Shaving & Grooming',
        price: 20000,
        type: 'service',
        reqStaffRole: 'Capster / Barber',
        available: true,
      },
      {
        id: 'barber-5',
        name: 'Hair Tonic Treatment & Massage',
        category: 'Treatment & Cuci',
        price: 30000,
        type: 'service',
        reqStaffRole: 'Capster / Barber',
        available: true,
      },
      {
        id: 'barber-6',
        name: 'Semir Hitam / Pewarnaan Basic',
        category: 'Pewarnaan',
        price: 60000,
        type: 'service',
        reqStaffRole: 'Capster / Barber',
        available: true,
      },
      {
        id: 'barber-7',
        name: 'Pomade Matte Clay 100gr',
        category: 'Produk Rambut',
        price: 55000,
        type: 'product',
        reqStaffRole: 'Kasir',
        available: true,
        stock: 20,
      },
      {
        id: 'barber-8',
        name: 'Hair Tonic Ginseng Spray',
        category: 'Produk Rambut',
        price: 45000,
        type: 'product',
        reqStaffRole: 'Kasir',
        available: true,
        stock: 15,
      },
    ],
  },
  salon: {
    id: 'salon',
    name: 'Salon Kecantikan & Spa',
    tagline: 'Perawatan rambut, facial, manicure, pedicure, & eyelash',
    icon: 'Sparkles',
    identifierLabel: 'No. Kursi / Nama Tamu',
    defaultStaffRoles: ['Hair Stylist', 'Beautician', 'Therapist', 'Nail Artist', 'Kasir'],
    defaultCategories: ['Hair Styling', 'Hair Treatment', 'Facial & Skincare', 'Nail Art & Eyelash', 'Body Care', 'Produk Salon'],
    defaultPaymentMethods: ['Cash', 'QRIS', 'Debit / Transfer'],
    defaultItems: [
      {
        id: 'salon-1',
        name: 'Cuci + Blow + Catok Variasi',
        category: 'Hair Styling',
        price: 50000,
        type: 'service',
        reqStaffRole: 'Hair Stylist',
        available: true,
      },
      {
        id: 'salon-2',
        name: 'Hair Spa L’Oreal + Pijat Punggung',
        category: 'Hair Treatment',
        price: 90000,
        type: 'service',
        reqStaffRole: 'Hair Stylist',
        available: true,
      },
      {
        id: 'salon-3',
        name: 'Smoothing / Rebonding Sutra',
        category: 'Hair Styling',
        price: 250000,
        type: 'service',
        reqStaffRole: 'Hair Stylist',
        available: true,
      },
      {
        id: 'salon-4',
        name: 'Facial Glowing Anti-Aging',
        category: 'Facial & Skincare',
        price: 135000,
        type: 'service',
        reqStaffRole: 'Beautician',
        available: true,
      },
      {
        id: 'salon-5',
        name: 'Manicure + Gel Nail Art',
        category: 'Nail Art & Eyelash',
        price: 85000,
        type: 'service',
        reqStaffRole: 'Nail Artist',
        available: true,
      },
      {
        id: 'salon-6',
        name: 'Pijat Tradisional Refleksi 60 Menit',
        category: 'Body Care',
        price: 100000,
        type: 'service',
        reqStaffRole: 'Therapist',
        available: true,
      },
      {
        id: 'salon-7',
        name: 'Serum Keratin Vitamin Rambut',
        category: 'Produk Salon',
        price: 65000,
        type: 'product',
        reqStaffRole: 'Kasir',
        available: true,
        stock: 12,
      },
    ],
  },
  fnb: {
    id: 'fnb',
    name: 'Food & Beverage (Resto/Cafe)',
    tagline: 'Restoran, cafe, warmindo, kedai kopi, & warung makan',
    icon: 'Utensils',
    identifierLabel: 'No. Meja / Pemesan',
    defaultStaffRoles: ['Kitchen / Dapur', 'Barista', 'Waiter', 'Kasir'],
    defaultCategories: ['Makanan Utama', 'Minuman', 'Camilan & Snack', 'Paket Hemat', 'Topping & Tambahan'],
    defaultPaymentMethods: ['Cash', 'QRIS', 'Shopeefood', 'Gofood', 'Grabfood'],
    defaultItems: [
      {
        id: 'fnb-1',
        name: 'Indomie Goreng Spesial Telur Kornet',
        category: 'Makanan Utama',
        price: 15000,
        type: 'product',
        reqStaffRole: 'Kitchen / Dapur',
        available: true,
      },
      {
        id: 'fnb-2',
        name: 'Nasi Goreng Spesial Seafood',
        category: 'Makanan Utama',
        price: 25000,
        type: 'product',
        reqStaffRole: 'Kitchen / Dapur',
        available: true,
      },
      {
        id: 'fnb-3',
        name: 'Kopi Susu Gula Aren Barista',
        category: 'Minuman',
        price: 16000,
        type: 'product',
        reqStaffRole: 'Barista',
        available: true,
      },
      {
        id: 'fnb-4',
        name: 'Es Teh Manis Jumbo Segar',
        category: 'Minuman',
        price: 6000,
        type: 'product',
        reqStaffRole: 'Barista',
        available: true,
      },
      {
        id: 'fnb-5',
        name: 'Kentang Goreng French Fries + Sosis',
        category: 'Camilan & Snack',
        price: 18000,
        type: 'product',
        reqStaffRole: 'Kitchen / Dapur',
        available: true,
      },
      {
        id: 'fnb-6',
        name: 'Paket Kenyang Hemat Siang',
        category: 'Paket Hemat',
        price: 30000,
        type: 'product',
        reqStaffRole: 'Kitchen / Dapur',
        available: true,
      },
    ],
  },
  retail: {
    id: 'retail',
    name: 'Retail & Toko Kelontong / Minimarket',
    tagline: 'Toko sembako, busana, minimarket, & toko retail',
    icon: 'Store',
    identifierLabel: 'Nama Pelanggan / ID Member',
    defaultStaffRoles: ['Kasir', 'Pramuniaga', 'Gudang'],
    defaultCategories: ['Sembako & Pokok', 'Minuman Kemasan', 'Makanan Ringan', 'Perawatan Diri', 'Kebutuhan Rumah'],
    defaultPaymentMethods: ['Cash', 'QRIS', 'Debit / Transfer'],
    defaultItems: [
      {
        id: 'ret-1',
        name: 'Minyak Goreng Pouch 2 Liter',
        category: 'Sembako & Pokok',
        price: 36000,
        type: 'product',
        reqStaffRole: 'Kasir',
        available: true,
        stock: 50,
      },
      {
        id: 'ret-2',
        name: 'Beras Premium 5 Kg',
        category: 'Sembako & Pokok',
        price: 74000,
        type: 'product',
        reqStaffRole: 'Kasir',
        available: true,
        stock: 30,
      },
      {
        id: 'ret-3',
        name: 'Air Mineral Botol 600ml Dingin',
        category: 'Minuman Kemasan',
        price: 4000,
        type: 'product',
        reqStaffRole: 'Kasir',
        available: true,
        stock: 120,
      },
      {
        id: 'ret-4',
        name: 'Keripik Kentang Renyah 75g',
        category: 'Makanan Ringan',
        price: 12000,
        type: 'product',
        reqStaffRole: 'Kasir',
        available: true,
        stock: 45,
      },
    ],
  },
  laundry: {
    id: 'laundry',
    name: 'Laundry Kiloan & Satuan',
    tagline: 'Cuci komplit, dry clean, setrika, bedcover, & express',
    icon: 'Shirt',
    identifierLabel: 'No. Nota / Nama Pelanggan',
    defaultStaffRoles: ['Operator Cuci', 'Petugas Setrika', 'Kasir'],
    defaultCategories: ['Cuci Komplit', 'Cuci Kering Lipat', 'Setrika Saja', 'Satuan & Bedcover', 'Paket Express'],
    defaultPaymentMethods: ['Cash', 'QRIS', 'Transfer Bank'],
    defaultItems: [
      {
        id: 'ld-1',
        name: 'Cuci Komplit Reguler (per Kg)',
        category: 'Cuci Komplit',
        price: 8000,
        type: 'service',
        reqStaffRole: 'Operator Cuci',
        available: true,
      },
      {
        id: 'ld-2',
        name: 'Cuci Komplit Express 1 Hari (per Kg)',
        category: 'Paket Express',
        price: 15000,
        type: 'service',
        reqStaffRole: 'Operator Cuci',
        available: true,
      },
      {
        id: 'ld-3',
        name: 'Setrika Uap Wangi (per Kg)',
        category: 'Setrika Saja',
        price: 5000,
        type: 'service',
        reqStaffRole: 'Petugas Setrika',
        available: true,
      },
      {
        id: 'ld-4',
        name: 'Cuci Bedcover Besar (King Size)',
        category: 'Satuan & Bedcover',
        price: 35000,
        type: 'service',
        reqStaffRole: 'Operator Cuci',
        available: true,
      },
      {
        id: 'ld-5',
        name: 'Parfum Laundry Grade A 250ml',
        category: 'Satuan & Bedcover',
        price: 25000,
        type: 'product',
        reqStaffRole: 'Kasir',
        available: true,
        stock: 20,
      },
    ],
  },
  workshop: {
    id: 'workshop',
    name: 'Bengkel & Servis Kendaraan',
    tagline: 'Servis rutin, ganti oli, tune-up, tambal ban & sparepart',
    icon: 'Wrench',
    identifierLabel: 'No. Polisi / Nama Pemilik',
    defaultStaffRoles: ['Mekanik 1', 'Mekanik 2', 'Kepala Bengkel', 'Kasir'],
    defaultCategories: ['Jasa Servis', 'Oli & Pelumas', 'Sparepart Motor', 'Ban & Tubeless', 'Perawatan Ringan'],
    defaultPaymentMethods: ['Cash', 'QRIS', 'Transfer Bank'],
    defaultItems: [
      {
        id: 'ws-1',
        name: 'Jasa Servis Ringan + Tune Up Karbu/Injeksi',
        category: 'Jasa Servis',
        price: 45000,
        type: 'service',
        reqStaffRole: 'Mekanik 1',
        available: true,
      },
      {
        id: 'ws-2',
        name: 'Oli Mesin Matic 10W-40 0.8L + Jasa Ganti',
        category: 'Oli & Pelumas',
        price: 55000,
        type: 'product',
        reqStaffRole: 'Mekanik 1',
        available: true,
        stock: 25,
      },
      {
        id: 'ws-3',
        name: 'Oli Gardan Matic',
        category: 'Oli & Pelumas',
        price: 18000,
        type: 'product',
        reqStaffRole: 'Mekanik 1',
        available: true,
        stock: 30,
      },
      {
        id: 'ws-4',
        name: 'Jasa Tambal Ban Tubeless Press',
        category: 'Ban & Tubeless',
        price: 20000,
        type: 'service',
        reqStaffRole: 'Mekanik 2',
        available: true,
      },
      {
        id: 'ws-5',
        name: 'Kampas Rem Depan Original',
        category: 'Sparepart Motor',
        price: 40000,
        type: 'product',
        reqStaffRole: 'Mekanik 1',
        available: true,
        stock: 10,
      },
    ],
  },
  custom: {
    id: 'custom',
    name: 'Usaha Jasa & Bisnis Lainnya',
    tagline: 'Konfigurasi fleksibel untuk usaha kreatif, klinik, fotokopi, dll.',
    icon: 'Briefcase',
    identifierLabel: 'Nama Klien / No. Pesanan',
    defaultStaffRoles: ['Petugas Pelaksana', 'Staff Lapangan', 'Kasir'],
    defaultCategories: ['Jasa Utama', 'Layanan Tambahan', 'Barang / Material', 'Konsultasi'],
    defaultPaymentMethods: ['Cash', 'QRIS', 'Transfer Bank'],
    defaultItems: [
      {
        id: 'cst-1',
        name: 'Paket Layanan Reguler',
        category: 'Jasa Utama',
        price: 50000,
        type: 'service',
        reqStaffRole: 'Petugas Pelaksana',
        available: true,
      },
      {
        id: 'cst-2',
        name: 'Layanan Tambahan / Custom',
        category: 'Layanan Tambahan',
        price: 25000,
        type: 'service',
        reqStaffRole: 'Petugas Pelaksana',
        available: true,
      },
      {
        id: 'cst-3',
        name: 'Barang / Material Pendukung',
        category: 'Barang / Material',
        price: 35000,
        type: 'product',
        reqStaffRole: 'Kasir',
        available: true,
        stock: 10,
      },
    ],
  },
};
