import { Customer, MembershipReward, MembershipRewardType, MembershipVisit } from '../types';
import { auth, db } from '../config/firebase';
import { doc, getDoc, setDoc } from 'firebase/firestore';
import { LEGACY_BARBERSHOP_REWARDS } from './membershipRewardService';

function requireMerchantId(merchantId: string): string { const id = String(merchantId || '').trim(); if (!id || id === 'default' || id === 'merchant_default') throw new Error('Merchant authentication is required before accessing customer data.'); const authUid = auth.currentUser?.uid?.trim(); if (!authUid || authUid !== id) throw new Error('Merchant identity does not match the authenticated Firebase user.'); return id; }
function sanitizeFirestoreData<T>(value: T): T { if (value === undefined) return undefined as T; if (Array.isArray(value)) return value.map((item) => sanitizeFirestoreData(item)).filter((item) => item !== undefined) as T; if (value !== null && typeof value === 'object' && !(value instanceof Date)) { const output: Record<string, unknown> = {}; for (const [key, item] of Object.entries(value as Record<string, unknown>)) { if (item !== undefined) output[key] = sanitizeFirestoreData(item); } return output as T; } return value; }

const syncQueues = new Map<string, Promise<boolean>>();
function enqueueSync(key: string, operation: () => Promise<boolean>): Promise<boolean> { const previous = syncQueues.get(key) || Promise.resolve(true); const next = previous.catch(() => false).then(operation); syncQueues.set(key, next); void next.finally(() => { if (syncQueues.get(key) === next) syncQueues.delete(key); }); return next; }

export function generateCustomerCode(name: string, phone: string): string { const lettersOnly = name.trim().replace(/[^a-zA-Z]/g, '').toUpperCase(); const namePrefix = lettersOnly.length >= 2 ? lettersOnly.substring(0, 2) : (lettersOnly + 'CU').substring(0, 2); const digitsOnly = phone.replace(/[^0-9]/g, ''); const phoneSuffix = digitsOnly.length >= 4 ? digitsOnly.slice(-4) : digitsOnly.padStart(4, '0'); return `${namePrefix}${phoneSuffix}`; }
export const initialCustomers: Customer[] = [];
export function getCustomerStorageKey(merchantId: string): string { return `yupos_${requireMerchantId(merchantId)}_customers`; }
export function loadCustomers(merchantId: string): Customer[] { if (!String(merchantId || '').trim()) return []; try { const raw = localStorage.getItem(getCustomerStorageKey(merchantId)); if (!raw) return []; const parsed = JSON.parse(raw) as Customer[]; return parsed.map((customer) => ({ ...customer, visitHistory: Array.isArray(customer.visitHistory) ? customer.visitHistory : (Array.isArray(customer.membershipVisits) ? customer.membershipVisits : []), membershipVisits: Array.isArray(customer.membershipVisits) ? customer.membershipVisits : [], membershipRedemptions: Array.isArray(customer.membershipRedemptions) ? customer.membershipRedemptions : [] })); } catch { return []; } }
export function saveCustomers(merchantId: string, customers: Customer[], persistToCache = false): void { if (!merchantId || !persistToCache) return; try { localStorage.setItem(getCustomerStorageKey(merchantId), JSON.stringify(customers)); } catch (err) { console.warn('Customer local cache write failed:', err); } }
export async function hydrateCustomersFromFirebase(merchantId: string): Promise<boolean> { try { const id = requireMerchantId(merchantId); const snapshot = await getDoc(doc(db, 'yupos_crm', id, 'customers', 'data')); if (!snapshot.exists()) return false; const list = snapshot.data().list; if (!Array.isArray(list)) return false; saveCustomers(id, list as Customer[], true); return true; } catch (err) { console.error('Firebase customer hydration failed:', err); return false; } }
export function syncCustomersToFirebase(merchantId: string, customers: Customer[]): Promise<boolean> { return enqueueSync(`customers:${merchantId}`, async () => { try { const id = requireMerchantId(merchantId); const payload = sanitizeFirestoreData({ list: customers.map((c) => ({ ...c, merchantId: id })), merchantId: id, updatedAt: Date.now() }); await setDoc(doc(db, 'yupos_crm', id, 'customers', 'data'), payload, { merge: true }); saveCustomers(id, customers, true); return true; } catch (err) { console.error('Firebase customer sync failed:', err); return false; } }); }
export function searchCustomerList(customers: Customer[], query: string): Customer[] { if (!query?.trim()) return customers; const q = query.trim().toLowerCase(); return customers.filter((c) => c.name.toLowerCase().includes(q) || c.customerCode.toLowerCase().includes(q) || c.phone.includes(q)); }
export interface CustomerVisitMeta { orderId?: string; services?: string[]; staff?: string[]; date?: string; time?: string; }
type LegacyReward = 'discount50' | 'freeHaircut';
interface PendingReward { customerCode?: string; reward?: MembershipReward | LegacyReward; createdAt?: number; }
function readPendingReward(merchantId: string, customerCode: string): MembershipReward | null { try { const raw = localStorage.getItem(`yupos_${merchantId}_pending_membership_reward`); if (!raw) return null; const pending = JSON.parse(raw) as PendingReward; if (Date.now() - Number(pending.createdAt || 0) >= 15 * 60 * 1000) return null; if (String(pending.customerCode || '').toUpperCase() !== customerCode.toUpperCase()) return null; if (typeof pending.reward === 'object' && pending.reward?.id) return pending.reward; if (pending.reward === 'discount50') return LEGACY_BARBERSHOP_REWARDS[0]; if (pending.reward === 'freeHaircut') return LEGACY_BARBERSHOP_REWARDS[1]; return null; } catch { return null; } }
export function setPendingMembershipReward(merchantId: string, customerCode: string, reward: MembershipReward | MembershipRewardType | LegacyReward): void { const id = requireMerchantId(merchantId); let normalized: MembershipReward | null = typeof reward === 'object' ? reward : LEGACY_BARBERSHOP_REWARDS.find((item) => reward === 'discount50' ? item.id === 'legacy-discount50' : item.id === 'legacy-freeHaircut') || null; if (!normalized) return; localStorage.setItem(`yupos_${id}_pending_membership_reward`, JSON.stringify({ customerCode, reward: normalized, createdAt: Date.now() })); }
function clearPendingReward(merchantId: string): void { try { localStorage.removeItem(`yupos_${merchantId}_pending_membership_reward`); } catch {} }
function resolveBusinessType(merchantId: string): string { try { return String(JSON.parse(localStorage.getItem(`yupos_${merchantId}_settings`) || '{}')?.businessType || 'barbershop'); } catch { return 'barbershop'; } }
function resolveLatestOrderVisitMeta(merchantId: string, customerCode: string): CustomerVisitMeta { try { const businessType = resolveBusinessType(merchantId); const orders = JSON.parse(localStorage.getItem(`yupos_${merchantId}_${businessType}_orders`) || '[]') as any[]; const latest = orders.filter((o) => o?.status === 'selesai' && String(o?.customerCode || '').toUpperCase() === customerCode.toUpperCase()).sort((a,b)=>Number(b?.timestamp||0)-Number(a?.timestamp||0))[0]; if (!latest) return {}; const items = Array.isArray(latest.items) ? latest.items : []; return { orderId: String(latest.id || ''), date: String(latest.date || ''), time: String(latest.time || ''), services: items.map((i)=>`${i?.name||'Item'}${Number(i?.qty||1)>1?` x${i.qty}`:''}`), staff: Array.from(new Set(items.map((i)=>String(i?.assignedTo||'').trim()).filter(Boolean))) }; } catch { return {}; } }
export async function recordCustomerVisit(customers: Customer[], customerData: { name: string; phone: string; customerCode?: string; isMember?: boolean }, transactionAmount = 0, merchantId = '', visitMeta: CustomerVisitMeta = {}): Promise<Customer[] | null> { if (transactionAmount <= 0 || !String(merchantId||'').trim()) return customers; const code=customerData.customerCode||generateCustomerCode(customerData.name,customerData.phone); const existingIdx=customers.findIndex(c=>c.customerCode.toUpperCase()===code.toUpperCase()||c.phone===customerData.phone); const now=new Date(); const fallbackDate=now.toISOString().split('T')[0]; const fallbackTime=now.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}); const autoMeta=resolveLatestOrderVisitMeta(merchantId,code); const resolvedMeta={...autoMeta,...visitMeta}; const visit:MembershipVisit={id:`VIS-${Date.now().toString(36).toUpperCase()}`,date:resolvedMeta.date||fallbackDate,time:resolvedMeta.time||fallbackTime,amount:transactionAmount,orderId:resolvedMeta.orderId,services:resolvedMeta.services||[],staff:resolvedMeta.staff||[]}; let updatedList:Customer[]; if(existingIdx>-1){const existing=customers[existingIdx];const shouldBeMember=customerData.isMember!==undefined?(customerData.isMember||existing.isMember):existing.isMember;const reward=shouldBeMember?readPendingReward(merchantId,code):null;const nextVisitCount=reward?1:(existing.visitCount||0)+1;const nextRedemptions=reward?[...(existing.membershipRedemptions||[]),{id:`REWARD-${Date.now().toString(36).toUpperCase()}`,rewardId:reward.id,type:reward.type,rewardName:reward.name,date:visit.date,visitCount:existing.visitCount||0}]:existing.membershipRedemptions||[];updatedList=[...customers];updatedList[existingIdx]={...existing,name:customerData.name.trim()||existing.name,phone:customerData.phone.trim()||existing.phone,customerCode:code,visitCount:nextVisitCount,isMember:shouldBeMember,memberSince:shouldBeMember&&!existing.isMember?visit.date:existing.memberSince,totalSpent:(existing.totalSpent||0)+transactionAmount,lastVisit:visit.date,visitHistory:[...(existing.visitHistory||existing.membershipVisits||[]),visit],membershipVisits:shouldBeMember?(reward?[visit]:[...(existing.membershipVisits||[]),visit]):existing.membershipVisits||[],membershipRedemptions:nextRedemptions};if(reward)clearPendingReward(merchantId);}else{const isMember=!!customerData.isMember;updatedList=[{id:`CUST-${Date.now().toString(36).toUpperCase()}`,name:customerData.name.trim(),phone:customerData.phone.trim(),customerCode:code,visitCount:1,isMember,memberSince:isMember?visit.date:undefined,totalSpent:transactionAmount,lastVisit:visit.date,createdAt:Date.now(),visitHistory:[visit],membershipVisits:isMember?[visit]:[],membershipRedemptions:[]},...customers];} const persisted = await syncCustomersToFirebase(merchantId,updatedList); return persisted ? updatedList : null; }
export async function claimMembershipReward(customers: Customer[], customerId: string, reward: MembershipReward | LegacyReward, merchantId: string): Promise<{customers:Customer[];success:boolean;message:string}>{try{requireMerchantId(merchantId);}catch{return{customers,success:false,message:'Merchant tidak terautentikasi.'}};const index=customers.findIndex(c=>c.id===customerId);if(index<0)return{customers,success:false,message:'Customer tidak ditemukan.'};const customer=customers[index];const normalized=typeof reward==='object'?reward:(reward==='discount50'?LEGACY_BARBERSHOP_REWARDS[0]:LEGACY_BARBERSHOP_REWARDS[1]);const visits=customer.visitCount||0;if(!customer.isMember)return{customers,success:false,message:'Customer belum terdaftar sebagai member.'};if(visits<Number(normalized.requiredVisits||0))return{customers,success:false,message:`Reward "${normalized.name}" membutuhkan minimal ${normalized.requiredVisits} kunjungan.`};const updated=[...customers];updated[index]={...customer,visitCount:0,membershipVisits:[],visitHistory:[...(customer.visitHistory||customer.membershipVisits||[])],membershipRedemptions:[...(customer.membershipRedemptions||[]),{id:`REWARD-${Date.now().toString(36).toUpperCase()}`,rewardId:normalized.id,type:normalized.type,rewardName:normalized.name,date:new Date().toISOString().split('T')[0],visitCount:visits}]};const persisted = await syncCustomersToFirebase(merchantId,updated); if (!persisted) return{customers,success:false,message:'Gagal menyimpan reward customer ke cloud.'}; return{customers:updated,success:true,message:`${normalized.name} berhasil diklaim. Siklus membership direset, riwayat customer tetap tersimpan.`};}
